apiVersion: v1
kind: Service
metadata:
  name: k8s-viz
  labels:
    app: k8s-viz
spec:
  ports:
  - port: 80
    targetPort: "http-server"
    nodePort: 30092
  selector:
    app: k8s-viz
  type: NodePort

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: k8s-viz
spec:
  replicas: 1
  template:
    metadata:
      labels:
       app: k8s-viz
    spec:
      containers:
      - name: k8s-viz
        image: moretea/k8s-viz:latest
        imagePullPolicy: Never
        ports:
          - name: http-server
            containerPort: 9292
